language: python
env:
  global:
  - secure: GaAguRxF+QilM0/DBfG7lZNdv4vtRpLGBLXrrLgeK53nEd71rtRS4CN8bDlSvSfGRvJP1kSGBAeQ8GfdQMalk1X4k2rOdoE2wUI16hffDaiiIep0NgIP0AAyk6lArCMZDvQsSzhNymO1ecUd37BB9fIyyrOPFrrOA0yRh3DVJGU=
  - secure: jvMgMwM/BY7+mIujPcCFKLOJl+HCChhNVUYTK4b7+kkn+bE7+5tfYrXcKsxt6hOY1YeKPtQJafsWgFmR9Rj1i0NzFA9oBPRgtavE3eLlPOLNRJaolY7A1FQwKTS3X5IbHyHb9hhKz1q916nDY14bkKP35HmtN14k4RozhdiXqRk=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev libatlas-dev libatlas-base-dev liblapack-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose coverage cpp-coveralls pillow
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout
script:
- ./bin/python -c 'from bob.db.verafinger import get_config; print(get_config())'
- ./bin/bob_dbmanage.py verafinger download
- ./bin/coverage run --source=bob.db.verafinger ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
